name: neo.io and neo.rawio tests

on:
  pull_request:
    branches: [master, gh_actions_and_datalad]
    types: [synchronize, opened, reopened, ready_for_review]

jobs:
  build-and-test:
    name: Test on (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # "macos-latest", "windows-latest"
        os: ["ubuntu-latest", ]
    steps:
      - uses: actions/checkout@v2
        with:
          python-version: 3.8
      - uses: actions/cache@v2
        id: cache-venv
        with:
          path: ~/test_env
          key: ${{ runner.os }}-venv-${{ hashFiles('**/requirements.txt') }}-${{ hashFiles('**/requirements_testing.txt') }}
          restore-keys: |
            ${{ runner.os }}-venv-
      - name: Install dependencies
        run: |
          # this is for datalad and download testing datasets
          sudo apt install git git-annex
          # needed for correct operation of git/git-annex/DataLad
          git config --global user.email "neo_ci@fake_mail.com"
          git config --global user.name "neo CI"
          # create an environement and install everything
          python -m venv ~/test_env
          source ~/test_env/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements_testing.txt
          pip install -e .
      - name: Get ephy_testing_data current head hash
        # the key depend on the last comit repo https://gin.g-node.org/NeuralEnsemble/ephy_testing_data.git
        id: vars
        run: |
          echo "::set-output name=HASH_EPHY_DATASET::$(git ls-remote https://gin.g-node.org/NeuralEnsemble/ephy_testing_data.git HEAD | cut -f1)"
      - uses: actions/cache@v2
        id: cache-datasets
        with:
          path: ~/ephy_testing_data
          key: ${{ runner.os }}-datasets-${{ steps.vars.outputs.HASH_EPHY_DATASET }}
          restore-keys: |
            ${{ runner.os }}-datasets
      - name: Test with pytest
        run: |
          source ~/test_env/bin/activate
          # onbly neo.rawio and neo.io
          pytest --cov=neo neo/test/rawiotest
          pytest --cov=neo neo/test/iotest
